[package]
name = "mojiji"
version = "0.1.0"
edition = "2021"

[dependencies]
rocket = { version = "0.5", features = ["json"] }
image = "0.25.0"
imageproc = "0.25.0"
rusttype = "0.9.2"
rand = "0.9.0"
ab_glyph = "0.2.29"
comrak = "0.37.0"
