[package]
name = "mojiji"
version = "0.1.0"
edition = "2021"

[dependencies]
rocket = { version = "0.5", features = ["json"] }
image = "0.23.14"
imageproc = "0.22.0"
rusttype = "0.9.2"
rand = "0.9.0"
